### PR TITLE
Fix atom 1.0 deprecations

### PR DESCRIPTION
**Pull request by ArnaudRinquin**
Just rename `scoped-properties` directory to `settings`

### CODE REVIEW

**Comment by ArnaudRinquin** [comment]
@devongovett Hey mate, you're extension will stop working in ~7 days. Please merge and publish this on before people can't use it, or transfer ownership if you don't want to maintain it anymore.

**Comment by devongovett** [comment]
Would you like to maintain this package? I no longer use Atom.

**Comment by ArnaudRinquin** [comment]
Well, it's not that would _like_ do maintain it but I can do it. It's not a lot of work.

**Comment by devongovett** [comment]
You're now a collaborator on the repo. This should also give you publish access to the atom package manager.

**Comment by ArnaudRinquin** [comment]
Great. I'll merge and publish this one then.

**Pull request merged**
